site_name: Build Site Manager 
theme:
  name: material
  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: indigo 
        accent: indigo
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  locales:
    fr:
    en:

plugins:
  - glightbox
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: fr
          default: true
          name: Français
          build: true

        - locale: en
          name: English
          build: true
          nav_translations:
            Accueil: Home
            S'enregistrer: Register
            Société: Company
            Projet: Project
            Autorisation sur les tâches: Task authorizations
            Type de temps: Time type
            Saisie des heures: Scheduler

nav:
  - Accueil: index.md
  - S'enregistrer: register.md
  - Société: company.md
  - Projet: project.md
  - Autorisation sur les tâches: task_authorization.md
  - Type de temps: time_type.md
  - Saisie des heures: scheduler.md
